name: deploy-workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of the env'
        required: true
        default: 'test'
jobs:
   job1:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@main
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        #with:
        #client-id: ${{ secrets.AZURE_CREDENTIALS }}
        #tenant-id: ${{ secrets.AZURE_CREDENTIALS }}
        #  subscription-id: ${{ secrets.AZURE_CREDENTIALS }}
          #clientSecret: ${{secrets.AZURE_CREDENTIALS }}
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
         subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         resourceGroupName: ${{ vars.RESOURCE_GROUP }}
         template: ./InfrastructureAsCode/main.bicep
         parameters: 'environment=${{ github.event.inputs.environment }}'
         failOnStdErr: false
