name:first-workflow

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  name: Job1
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Step1
        run: echo Step2
