name: first-workflow
on: workflow_dispatch 
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Step1
      - name: Run another one-line script
        run: echo Step2
